steps:
  # Étape 1 : Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/recommendation-api', 
      '.'
    ]

  # Étape 2 : Push de l'image dans Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/recommendation-api'
    ]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/recommendation-api'

substitutions:
  _REGION: europe-west1
  _REPOSITORY: recommendation
